import { CategoryRule } from '../types';

// Predefined categories
export const predefinedCategories = [
  "Food", "Transport", "Dining", "Housing", "Utilities", "Entertainment",
  "Healthcare", "Education", "Clothing", "Travel", "Insurance", "Personal Care",
  "Gifts", "Savings", "Other"
];

// Auto-categorization rules
export const autoCatRules: CategoryRule[] = [
  // Food & Groceries
  { keyword: "grocer", category: "Food" },
  { keyword: "tesco", category: "Food" },
  { keyword: "sainsbury", category: "Food" },
  { keyword: "asda", category: "Food" },
  { keyword: "aldi", category: "Food" },
  { keyword: "lidl", category: "Food" },
  { keyword: "waitrose", category: "Food" },
  { keyword: "morrisons", category: "Food" },
  { keyword: "m&s food", category: "Food" },
  { keyword: "co-op", category: "Food" },
  { keyword: "iceland", category: "Food" },
  { keyword: "farmfoods", category: "Food" },
  { keyword: "chips", category: "Food" },
  { keyword: "crisps", category: "Food" },
  { keyword: "bread", category: "Food" },
  { keyword: "milk", category: "Food" },
  { keyword: "cheese", category: "Food" },
  { keyword: "fruit", category: "Food" },
  { keyword: "veg", category: "Food" },
  { keyword: "meat", category: "Food" },
  { keyword: "chicken", category: "Food" },
  { keyword: "fish", category: "Food" },
  { keyword: "hello fresh", category: "Food" },
  { keyword: "gousto", category: "Food" },
  { keyword: "food", category: "Food" },
  { keyword: "snack", category: "Food" },
  { keyword: "grocery", category: "Food" },
  { keyword: "supermarket", category: "Food" },

  // Transport
  { keyword: "uber", category: "Transport" },
  { keyword: "bolt", category: "Transport" },
  { keyword: "taxi", category: "Transport" },
  { keyword: "bus", category: "Transport" },
  { keyword: "train", category: "Transport" },
  { keyword: "tube", category: "Transport" },
  { keyword: "oyster", category: "Transport" },
  { keyword: "tfl", category: "Transport" },
  { keyword: "national rail", category: "Transport" },
  { keyword: "fuel", category: "Transport" },
  { keyword: "petrol", category: "Transport" },
  { keyword: "diesel", category: "Transport" },
  { keyword: "shell", category: "Transport" },
  { keyword: "esso", category: "Transport" },
  { keyword: "bp", category: "Transport" },
  { keyword: "texaco", category: "Transport" },
  { keyword: "parking", category: "Transport" },
  { keyword: "congestion", category: "Transport" },
  { keyword: "mot", category: "Transport" },
  { keyword: "car service", category: "Transport" },
  { keyword: "car wash", category: "Transport" },
  { keyword: "vehicle", category: "Transport" },

  // Dining & Restaurants
  { keyword: "mcdonald", category: "Dining" },
  { keyword: "burger king", category: "Dining" },
  { keyword: "kfc", category: "Dining" },
  { keyword: "nando", category: "Dining" },
  { keyword: "wagamama", category: "Dining" },
  { keyword: "pizza", category: "Dining" },
  { keyword: "domino", category: "Dining" },
  { keyword: "restaurant", category: "Dining" },
  { keyword: "cafe", category: "Dining" },
  { keyword: "coffee", category: "Dining" },
  { keyword: "starbucks", category: "Dining" },
  { keyword: "costa", category: "Dining" },
  { keyword: "pret", category: "Dining" },
  { keyword: "greggs", category: "Dining" },
  { keyword: "subway", category: "Dining" },
  { keyword: "takeaway", category: "Dining" },
  { keyword: "deliveroo", category: "Dining" },
  { keyword: "just eat", category: "Dining" },
  { keyword: "uber eats", category: "Dining" },
  { keyword: "pub", category: "Dining" },
  { keyword: "bar", category: "Dining" },
  { keyword: "wetherspoon", category: "Dining" },

  // Housing & Utilities
  { keyword: "rent", category: "Housing" },
  { keyword: "mortgage", category: "Housing" },
  { keyword: "council tax", category: "Housing" },
  { keyword: "council", category: "Housing" },
  { keyword: "home insurance", category: "Housing" },
  { keyword: "property", category: "Housing" },
  { keyword: "letting", category: "Housing" },
  { keyword: "estate agent", category: "Housing" },
  { keyword: "electric", category: "Utilities" },
  { keyword: "water", category: "Utilities" },
  { keyword: "gas", category: "Utilities" },
  { keyword: "internet", category: "Utilities" },
  { keyword: "broadband", category: "Utilities" },
  { keyword: "phone", category: "Utilities" },
  { keyword: "mobile", category: "Utilities" },
  { keyword: "virgin", category: "Utilities" },
  { keyword: "bt", category: "Utilities" },
  { keyword: "sky", category: "Utilities" },
  { keyword: "ee", category: "Utilities" },
  { keyword: "three", category: "Utilities" },
  { keyword: "vodafone", category: "Utilities" },
  { keyword: "o2", category: "Utilities" },

  // Entertainment
  { keyword: "cinema", category: "Entertainment" },
  { keyword: "odeon", category: "Entertainment" },
  { keyword: "vue", category: "Entertainment" },
  { keyword: "cineworld", category: "Entertainment" },
  { keyword: "movie", category: "Entertainment" },
  { keyword: "theatre", category: "Entertainment" },
  { keyword: "netflix", category: "Entertainment" },
  { keyword: "spotify", category: "Entertainment" },
  { keyword: "amazon prime", category: "Entertainment" },
  { keyword: "disney", category: "Entertainment" },
  { keyword: "now tv", category: "Entertainment" },
  { keyword: "game", category: "Entertainment" },
  { keyword: "playstation", category: "Entertainment" },
  { keyword: "xbox", category: "Entertainment" },
  { keyword: "nintendo", category: "Entertainment" },
  { keyword: "steam", category: "Entertainment" },
  { keyword: "concert", category: "Entertainment" },
  { keyword: "festival", category: "Entertainment" },
  { keyword: "ticket", category: "Entertainment" },
  { keyword: "bowling", category: "Entertainment" },
  { keyword: "arcade", category: "Entertainment" },

  // Healthcare
  { keyword: "doctor", category: "Healthcare" },
  { keyword: "gp", category: "Healthcare" },
  { keyword: "dentist", category: "Healthcare" },
  { keyword: "optician", category: "Healthcare" },
  { keyword: "pharmacy", category: "Healthcare" },
  { keyword: "boots", category: "Healthcare" },
  { keyword: "superdrug", category: "Healthcare" },
  { keyword: "prescription", category: "Healthcare" },
  { keyword: "medicine", category: "Healthcare" },
  { keyword: "vitamin", category: "Healthcare" },
  { keyword: "hospital", category: "Healthcare" },
  { keyword: "clinic", category: "Healthcare" },
  { keyword: "medical", category: "Healthcare" },
  { keyword: "health", category: "Healthcare" },
  { keyword: "nhs", category: "Healthcare" },
  { keyword: "therapy", category: "Healthcare" },
  { keyword: "counselling", category: "Healthcare" },

  // Education
  { keyword: "tuition", category: "Education" },
  { keyword: "course", category: "Education" },
  { keyword: "class", category: "Education" },
  { keyword: "training", category: "Education" },
  { keyword: "book", category: "Education" },
  { keyword: "textbook", category: "Education" },
  { keyword: "stationery", category: "Education" },
  { keyword: "udemy", category: "Education" },
  { keyword: "coursera", category: "Education" },
  { keyword: "skillshare", category: "Education" },
  { keyword: "school", category: "Education" },
  { keyword: "college", category: "Education" },
  { keyword: "university", category: "Education" },
  { keyword: "student", category: "Education" },
  { keyword: "education", category: "Education" },
  { keyword: "learning", category: "Education" },

  // Clothing
  { keyword: "clothing", category: "Clothing" },
  { keyword: "clothes", category: "Clothing" },
  { keyword: "apparel", category: "Clothing" },
  { keyword: "shoes", category: "Clothing" },
  { keyword: "boots", category: "Clothing" },
  { keyword: "trainers", category: "Clothing" },
  { keyword: "zara", category: "Clothing" },
  { keyword: "h&m", category: "Clothing" },
  { keyword: "uniqlo", category: "Clothing" },
  { keyword: "primark", category: "Clothing" },
  { keyword: "asos", category: "Clothing" },
  { keyword: "next", category: "Clothing" },
  { keyword: "topshop", category: "Clothing" },
  { keyword: "river island", category: "Clothing" },
  { keyword: "tk maxx", category: "Clothing" },
  { keyword: "sports direct", category: "Clothing" },
  { keyword: "jd sports", category: "Clothing" },
  { keyword: "nike", category: "Clothing" },
  { keyword: "adidas", category: "Clothing" },
  { keyword: "fashion", category: "Clothing" },

  // Travel
  { keyword: "flight", category: "Travel" },
  { keyword: "airline", category: "Travel" },
  { keyword: "british airways", category: "Travel" },
  { keyword: "easyjet", category: "Travel" },
  { keyword: "ryanair", category: "Travel" },
  { keyword: "hotel", category: "Travel" },
  { keyword: "airbnb", category: "Travel" },
  { keyword: "booking.com", category: "Travel" },
  { keyword: "expedia", category: "Travel" },
  { keyword: "holiday", category: "Travel" },
  { keyword: "vacation", category: "Travel" },
  { keyword: "travel", category: "Travel" },
  { keyword: "hostel", category: "Travel" },
  { keyword: "resort", category: "Travel" },
  { keyword: "cruise", category: "Travel" },
  { keyword: "passport", category: "Travel" },
  { keyword: "visa", category: "Travel" },
  { keyword: "tourist", category: "Travel" },

  // Insurance
  { keyword: "insurance", category: "Insurance" },
  { keyword: "premium", category: "Insurance" },
  { keyword: "policy", category: "Insurance" },
  { keyword: "aviva", category: "Insurance" },
  { keyword: "axa", category: "Insurance" },
  { keyword: "direct line", category: "Insurance" },
  { keyword: "admiral", category: "Insurance" },
  { keyword: "churchill", category: "Insurance" },
  { keyword: "comparethemarket", category: "Insurance" },
  { keyword: "moneysupermarket", category: "Insurance" },
  { keyword: "life insurance", category: "Insurance" },
  { keyword: "car insurance", category: "Insurance" },
  { keyword: "home insurance", category: "Insurance" },
  { keyword: "pet insurance", category: "Insurance" },
  { keyword: "travel insurance", category: "Insurance" },

  // Personal Care
  { keyword: "salon", category: "Personal Care" },
  { keyword: "haircut", category: "Personal Care" },
  { keyword: "hairdresser", category: "Personal Care" },
  { keyword: "barber", category: "Personal Care" },
  { keyword: "spa", category: "Personal Care" },
  { keyword: "massage", category: "Personal Care" },
  { keyword: "cosmetics", category: "Personal Care" },
  { keyword: "makeup", category: "Personal Care" },
  { keyword: "beauty", category: "Personal Care" },
  { keyword: "skincare", category: "Personal Care" },
  { keyword: "gym", category: "Personal Care" },
  { keyword: "fitness", category: "Personal Care" },
  { keyword: "personal trainer", category: "Personal Care" },
  { keyword: "nail", category: "Personal Care" },
  { keyword: "wax", category: "Personal Care" },
  { keyword: "grooming", category: "Personal Care" },

  // Gifts
  { keyword: "gift", category: "Gifts" },
  { keyword: "present", category: "Gifts" },
  { keyword: "card", category: "Gifts" },
  { keyword: "birthday", category: "Gifts" },
  { keyword: "christmas", category: "Gifts" },
  { keyword: "anniversary", category: "Gifts" },
  { keyword: "wedding", category: "Gifts" },
  { keyword: "celebration", category: "Gifts" },
  { keyword: "party", category: "Gifts" },
  { keyword: "moonpig", category: "Gifts" },
  { keyword: "funky pigeon", category: "Gifts" },
  { keyword: "flowers", category: "Gifts" },
  { keyword: "hamper", category: "Gifts" },

  // Savings
  { keyword: "savings", category: "Savings" },
  { keyword: "investment", category: "Savings" },
  { keyword: "isa", category: "Savings" },
  { keyword: "pension", category: "Savings" },
  { keyword: "stocks", category: "Savings" },
  { keyword: "shares", category: "Savings" },
  { keyword: "fund", category: "Savings" },
  { keyword: "transfer to savings", category: "Savings" },
  { keyword: "deposit", category: "Savings" },

  // Shopping & General
  { keyword: "amazon", category: "Other" },
  { keyword: "ebay", category: "Other" },
  { keyword: "argos", category: "Other" },
  { keyword: "currys", category: "Other" },
  { keyword: "john lewis", category: "Other" },
  { keyword: "wilko", category: "Other" },
  { keyword: "b&q", category: "Other" },
  { keyword: "homebase", category: "Other" },
  { keyword: "ikea", category: "Other" },
  { keyword: "dunelm", category: "Other" },
];

// Auto-categorize expense description
export const autoCategorizePurchase = (description: string, defaultCategory = "Other"): string => {
  const lowercaseDesc = description.toLowerCase().trim();
  
  for (const rule of autoCatRules) {
    if (lowercaseDesc.includes(rule.keyword.toLowerCase())) {
      return rule.category;
    }
  }
  
  return defaultCategory;
};